spring.application.name=FamilyHub

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/familyhub_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
app.jwt.secret=change-me-in-prod
app.jwt.ttl-seconds=3600
app.jwt.refresh-ttl-seconds=2592000

# Logging
logging.level.root=WARN
logging.level.com.visnevschi.familyhub=INFO