spring.application.name=FamilyHub

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:familydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# FORCE H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in the console (useful for debugging)
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true